[project]
name = "cfb-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dxcam-cpp>=0.2.5",
    "loguru>=0.7.3",
    "numpy>=2.5.1",
    "opencv-python>=5.0.0.93",
    "pywin32>=312",
    "vgamepad>=0.1.0",
]

[dependency-groups]
dev = [
    "marimo[lsp]>=0.23.14",
    "ruff>=0.15.22",
    "ty>=0.0.61",
    "types-pywin32>=312.0.0.20260609",
]

[tool.marimo.diagnostics]
enabled = true

[tool.marimo.language_servers.pylsp]
enabled = true
enable_mypy = false
enable_ruff = true
enable_flake8 = false
enable_pydocstyle = false
enable_pylint = false
enable_pyflakes = false

[tool.marimo.language_servers.ty]
enabled = true

[tool.marimo.display]
custom_css = ["notebooks/public/custom-theme.css"]
default_width = "medium"

[tool.ruff.lint]
extend-select = ["I"]
